from models.artist import Artist
from models.album import Album

import repositories.artist_repository as artist_repository
import repositories.album_repository as album_repository

album_repository.delete_all()
artist_repository.delete_all()

artist_1 = Artist("Biffy Clyro")
artist_2 = Artist("Brand New")
artist_3 = Artist("Rise Against")
artist_4 = Artist("Explosions In The Sky")
artist_5 = Artist("Elton John")
artist_6 = Artist("City and Colour")
artist_7 = Artist("Mogwai")
artist_8 = Artist("Skunk Anansie")
artist_9 = Artist("Eminem")
artist_10 = Artist("Hell Is For Heroes")
artist_repository.save(artist_1)
artist_repository.save(artist_2)
artist_repository.save(artist_3)
artist_repository.save(artist_4)
artist_repository.save(artist_5)
artist_repository.save(artist_6)
artist_repository.save(artist_7)
artist_repository.save(artist_8)
artist_repository.save(artist_9)
artist_repository.save(artist_10)

album_1 = Album(artist_1, "Opposites", 2018, "Rock", 10, 6.50, 11.99)
album_2 = Album(artist_2, "The Devil and God Are Raging Inside Me", 2006, "Alt rock", 5, 6.00, 9.99)
album_3 = Album(artist_3, "The Sufferer & the Witness", 2006, "Punk rock", 4, 5.00, 9.99)
album_4 = Album(artist_4, "The Earth Is Not a Cold Dead Place", 2003, "Post rock", 6, 6.00, 11.99)
album_5 = Album(artist_5, "Too Low for Zero", 1983, "Pop", 0, 8.00, 12.99)
album_6 = Album(artist_6, "Bring Me Your Love", 2008, "Alt rock", 7, 5.00, 9.99)
album_7 = Album(artist_7, "Les Revenants", 2013, "Post rock", 1, 8.00, 13.99)
album_8 = Album(artist_8, "Stoosh", 1996, "Hard rock", 7, 8.00, 9.99)
album_9 = Album(artist_9, "The Marshall Mathers LP", 2000, "Rap", 8, 4.00, 7.99)
album_10 = Album(artist_10, "The Neon Handshake", 2003, "Post hardcore", 4, 7.00, 12.99)
album_11 = Album(artist_1, "Blackened Sky", 2002, "Rock", 3, 5.00, 8.99)
album_12 = Album(artist_9, "Revival", 2017, "Rap", 6, 4.00, 6.99)
album_repository.save(album_1)
album_repository.save(album_2)
album_repository.save(album_3)
album_repository.save(album_4)
album_repository.save(album_5)
album_repository.save(album_6)
album_repository.save(album_7)
album_repository.save(album_8)
album_repository.save(album_9)
album_repository.save(album_10)
album_repository.save(album_11)
album_repository.save(album_12)
